import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_W } = Dimensions.get('window');
const PADDING = 16;

export default StyleSheet.create({
  card: {
    margin: PADDING,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 14,
    top: 56,
    marginBottom: -2.5,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  title: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    fontFamily: 'SpaceGrotesk-Regular',
  },
  badge: {
    backgroundColor: '#F0F8DA',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#333',
    fontFamily: 'SpaceGrotesk-Regular',
  },
  rangeContainer: {
    marginBottom: 12,
    marginHorizontal: -6,
  },
  rangeSegmentedControl: {
    height: 24,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
  },
  selectorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: -10,
  },
  selectorWrapper: {
    flex: 1,
    marginHorizontal: 4,
  },
  selectorControl: {
    width: '100%',
    height: 25,
    backgroundColor: '#f0f0f0',
    borderRadius: 7,
    fontFamily: 'SpaceGrotesk-Regular',
  },
  chartWrapper: {
    marginLeft: -10,
    width: SCREEN_W - PADDING * 2,
    top: 10,
  },
  yAxisText: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontWeight: '400',
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.04,
    color: '#999',
    marginLeft: -10,
  },
  tooltip: {
    position: 'absolute',
    flexDirection: 'row',
    backgroundColor: '#F0F8DA',
    padding: 6,
    borderRadius: 4,
    alignItems: 'center',
    zIndex: 1000,
  },
  tooltipArrowUp: {
    position: 'absolute',
    top: -4,
    left: '50%',
    marginLeft: -3,
    width: 0,
    height: 0,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderBottomWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#F0F8DA',
  },
  tooltipArrowDown: {
    position: 'absolute',
    bottom: -4,
    left: '50%',
    marginLeft: -3,
    width: 0,
    height: 0,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    borderTopWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#F0F8DA',
  },
  tooltipText: {
    color: 'black',
    fontWeight: '400',
    fontSize: 10,
    fontFamily: 'SpaceGrotesk-Regular',
  },
  tooltipDivider: {
    width: 1,
    height: 14,
    backgroundColor: '#DEE2E7',
    borderStyle: 'dashed',
    marginHorizontal: 4,
    alignSelf: 'center',
  },
  tooltipDateRow: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
  },
  tooltipSub: {
    color: '#93A071',
    fontSize: 10,
    fontFamily: 'SpaceGrotesk-Regular',
  },
  xLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    marginHorizontal: 17.5,
    left: 13,
  },
  xLabel: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontWeight: '400',
    fontSize: 10,
  },
  emptyChartContainer: {
    height: 220,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyChartText: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontSize: 14,
    color: '#999',
  },
});