import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 16,
    borderRadius: 10,
    width: 343,
    minHeight: 168,
  },
  titleContainer: {
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Medium',
    fontWeight: '500',
    color: '#000',
  },
  durationInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 15,
  },
  durationMinutes: {
    width: 143.5,
    height: 60,
  },
  labelText: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontWeight: '400',
    fontSize: 12,
    color: '#919EB0',
    alignSelf: 'center',
    marginBottom: 4,
  },
  boxDurationMinutes: {
    width: 143.5,
    height: 44,
    borderColor: '#919EB0',
    borderWidth: 0.75,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    fontFamily: 'SpaceGrotesk-Bold',
    fontSize: 32,
    textAlign: 'center',
    color: '#000',
    backgroundColor: 'transparent',
    width: '100%',
    height: '100%',
    padding: 0,
    margin: 0,
  },
  separator: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#000',
    alignSelf: 'center',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  buttonCancelSpray: {
    flex: 1,
    height: 36,
    borderColor: '#B4DC45',
    borderWidth: 1,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonStartSpray: {
    flex: 1,
    backgroundColor: '#B4DC45',
    borderRadius: 8,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelText: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontWeight: '500',
    fontSize: 14,
    color: '#353D48',
  },
  confirmText: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontWeight: '600',
    fontSize: 14,
    color: '#353D48',
  },
});