import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 16,
    marginTop: 15,
  },
  title: {
    fontSize: 16,
    fontFamily: 'SpaceGrotesk-Medium',
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 12,
  },
  tankRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  tankLabel: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontSize: 12,
    color: '#6B7280',
    width: 90,
  },
  tankBarWrapper: {
    flex: 1,
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
    overflow: 'hidden',
  },
  tankBar: {
    height: 8,
    backgroundColor: '#B4DC45',
    borderRadius: 4,
  },
  tankValue: {
    fontFamily: 'SpaceGrotesk-Medium',
    fontSize: 12,
    color: '#374151',
    width: 35,
    textAlign: 'right',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    marginBottom: 8,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 6,
  },
  statusText: {
    fontFamily: 'SpaceGrotesk-Medium',
    fontSize: 12,
    fontWeight: '600',
  },
  activeType: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 12,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  button: {
    flex: 1,
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
  },
  buttonPrep: {
    backgroundColor: '#FEF3C7',
  },
  buttonStart: {
    backgroundColor: '#B4DC45',
  },
  buttonDisabled: {
    opacity: 0.4,
  },
  buttonText: {
    fontFamily: 'SpaceGrotesk-Medium',
    fontSize: 13,
    fontWeight: '600',
    color: '#1F2937',
  },
  buttonSubText: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontSize: 10,
    color: '#6B7280',
    marginTop: 2,
    textAlign: 'center',
  },
  stopButton: {
    marginTop: 10,
    backgroundColor: '#FEE2E2',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
  },
  stopText: {
    fontFamily: 'SpaceGrotesk-Medium',
    fontSize: 13,
    fontWeight: '600',
    color: '#EF4444',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBox: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    width: '85%',
  },
  modalTitle: {
    fontFamily: 'SpaceGrotesk-Medium',
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
  },
  modalSub: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 16,
  },
  typeButton: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  typeButtonText: {
    fontFamily: 'SpaceGrotesk-Medium',
    fontSize: 14,
    color: '#1F2937',
  },
  typeButtonSub: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontSize: 11,
    color: '#9CA3AF',
    marginTop: 2,
  },
  durationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 20,
  },
  durationInput: {
    alignItems: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    width: 70,
    height: 44,
    textAlign: 'center',
    fontSize: 20,
    fontFamily: 'SpaceGrotesk-Medium',
    color: '#1F2937',
  },
  inputLabel: {
    fontFamily: 'SpaceGrotesk-Regular',
    fontSize: 11,
    color: '#9CA3AF',
    marginTop: 4,
  },
  durationSep: {
    fontSize: 24,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  cancelButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
  },
  cancelText: {
    fontFamily: 'SpaceGrotesk-Medium',
    fontSize: 13,
    color: '#6B7280',
  },
  startConfirmButton: {
    flex: 1,
    backgroundColor: '#B4DC45',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
  },
  startConfirmText: {
    fontFamily: 'SpaceGrotesk-Medium',
    fontSize: 13,
    fontWeight: '600',
    color: '#1F2937',
  },
});