import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  cardTwo: {
    width: '100%',
    height: 340,
    borderRadius: 16,
    overflow: 'hidden',
    padding: 11,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    backgroundColor: 'white',
    marginBottom: 2,
  },
  cardThree: {
    width: '100%',
    height: 500,
    borderRadius: 16,
    overflow: 'hidden',
    padding: 11,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    backgroundColor: 'white',
    marginBottom: 2,
  },
  cardContentTwo: {
    flex: 1,
    marginTop: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 8,
  },
  soilTitle: {
    fontSize: 16,
    fontWeight: '600',
    fontFamily: 'SpaceGrotesk-Medium',
    color: '#1F2937',
  },
  soilSubTitle: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'SpaceGrotesk-Medium',
    color: '#374151',
    marginBottom: 12,
  },
  gridContainer: {
    flex: 1,
    gap: 8,
  },
  gridRow: {
    flexDirection: 'row',
    gap: 8,
    height: 44,
  },
  gridItemEmpty: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  containerTransmisi: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 148,
    marginTop: 12,
    gap: 1,
    alignItems: 'center',
    marginBottom: 6,
  },
  cardTransmisi: {
    overflow: 'hidden',
    backgroundColor: 'white',
    flex: 1,
    height: 148,
    borderRadius: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  cardDetailTransmisi: {
    width: 160.5,
    paddingHorizontal: 4,
    height: 132,
    backgroundColor: 'white',
    gap: 4,
    marginTop: 8,
    alignItems: 'center',
  },
  Transmisi: {
    backgroundColor: 'white',
    width: 126,
    height: 112,
  },
  valueTransmisi: {
    position: 'absolute',
    fontSize: 40,
    fontWeight: '600',
    fontFamily: 'SpaceGrotesk-Regular',
    zIndex: 10,
    top: 45,
    textAlign: 'center',
    marginLeft: 10,
  },
  nameSensorTransmisi: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'SpaceGrotesk-Regular',
  },
  timestampContainer: {
    flexDirection:"row",
    marginTop: 4,
    marginBottom: 4,
    paddingVertical: 4
  },
  timestampLabel: {
    fontFamily:"SpaceGrotesk-Regular",
    fontSize: 11,
    color: '#6B7280'
  },
  timestampValue: {
    fontFamily: "SpaceGrotesk-Regular",
    fontSize: 11,
    color: "#B4DC45"
  },
});
