import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 100,
  },
  containerTransmisi: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 148,
    marginTop: 14,
    gap: 1,
    alignItems: 'center',
  },
  cardTransmisi: {
    overflow: 'hidden',
    backgroundColor: 'white',
    flex: 1,
    height: 148,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardDetailTransmisi: {
    width: 160.5,
    paddingHorizontal: 4,
    height: 132,
    backgroundColor: 'white',
    gap: 4,
    marginTop: 8,
    alignItems: 'center',
  },
  Transmisi: {
    backgroundColor: 'white',
    width: 126,
    height: 112,
  },
  valueTransmisi: {
    position: 'absolute',
    fontSize: 40,
    fontWeight: '600',
    fontFamily: 'SpaceGrotesk-Regular',
    zIndex: 10,
    top: 45,
    textAlign: 'center',
    marginLeft: 10,
  },
  nameSensorTransmisi: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'SpaceGrotesk-Regular',
  },

  cardTwo: {
    width: '100%',
    borderRadius: 16,
    overflow: 'hidden',
    padding: 12,
    marginTop: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    backgroundColor: 'white',
    marginBottom: 8,
    elevation: 2,
  },
  soilTitle: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'SpaceGrotesk-SemiBold',
  },
  soilStatisticOne: {
    height: 52,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 9,
    marginHorizontal: 1,
    gap: 8,
  },
  soilStatisticTwo: {
    height: 52,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
    marginHorizontal: 1,
    gap: 8,
  },
  detailStatisticOne: {
    paddingHorizontal: 8,
    flex: 1,
    height: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DEE2E7',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  detailStatisticOneKal: {
    paddingHorizontal: 8,
    flex: 0.47,
    height: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DEE2E7',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  statContent: {
    flex: 1,
    justifyContent: 'center',
  },
  statLabelHistory: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'SpaceGrotesk-Regular',
  },
  statValueHistory: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'SpaceGrotesk-SemiBold',
  },
  statExtra: {
    flexDirection: 'column',
    marginTop: 10,
    alignItems: 'center',
    marginLeft: 8,
  },
  statStatusHistory: {
    fontSize: 12.5,
    marginLeft: 4,
  },
  card: {
  backgroundColor: '#FFFFFF',
  borderRadius: 16,
  padding: 12,
  shadowColor: '#000',
  shadowOffset: {width: 0, height: 2},
  shadowOpacity: 0.05,
  shadowRadius: 8,
  elevation: 2,
},
cardTitle: {
  fontSize: 16,
  fontWeight: '600',
  color: '#1F2937',
  marginBottom: 16,
  fontFamily: 'SpaceGrotesk-Regular',
},
statRow: {
  flexDirection: 'row',
  gap: 8,
  marginBottom: 8,
},
statCard: {
  flex: 1,
  borderRadius: 12,
  padding: 6,
  borderWidth: 1,
  borderColor: '#E5E7EB',
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  minHeight: 50,
},
statCardPlaceholder: {
  flex: 1,
  opacity: 0,
},
statCardContent: {
  flex: 1,
},
statLabel: {
  fontSize: 12,
  color: '#6B7280',
  marginBottom: 4,
  fontFamily: 'SpaceGrotesk-Regular',
},
statValue: {
  fontSize: 14,
  fontWeight: '600',
  color: '#1F2937',
  fontFamily: 'SpaceGrotesk-Regular',
},
statIndicator: {
  alignItems: 'center',
  marginLeft: 8,
},
statStatus: {
  fontSize: 10,
  marginTop: 2,
  fontWeight: '500',
  fontFamily: 'SpaceGrotesk-Regular',
},
});
