import {StyleSheet, Platform} from 'react-native';


export const styles = StyleSheet.create({
  card: {
    width: '100%',
    height: 162,
    borderRadius: 16,
    overflow: 'hidden',
    padding: 1,
    marginTop: 12,
  },
  image: {
    borderRadius: 16,
  },
  location: {
    justifyContent: 'flex-start',
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingBottom: 100,
    marginLeft: -5,
    marginTop: 10,
    alignItems: 'center',
  },
  locationText: {
    fontSize: 14,
    fontFamily: 'SpaceGrotesk-Regular',
    fontWeight: '400',
    color: 'white',
    marginLeft: 4,
  },
  weatherSectionTwo: {
    width: 159,
    height: 44,
    backgroundColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    marginTop: -90,
    borderRadius: 12,
    gap: 10,
  },
  temperatureText: {
    fontSize: 40,
    fontFamily: 'SpaceGrotesk-Regular',
    color: 'white',
    fontWeight: '600',
    textAlign: 'center',
    top: -6,
  },
  detailSectionTwo: {
    flexDirection: 'column',
    gap: 1,
    alignContent: 'center',
  },
  detailSectionTwoText: {
    fontSize: 12,
    fontWeight: '400',
    fontFamily: 'SpaceGrotesk-Regular',
    color: 'white',
  },
  cloud: {
    position: 'absolute',
    height: 76.05,
    backgroundColor: 'transparent',
    marginBottom: 20,
    alignItems: 'center',
    justifyContent:"center",
  },
  gradientLine: {
    width: 319,
    height: 2,
    opacity: 0.62,
    marginTop: 20,
    alignSelf: 'center',
    borderRadius: 1,
    marginBottom: 10,
  },
  detailSectionThree: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    height: 36,
    width: '100%',
  },
  detailSectionThreeText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '600',
    fontFamily: 'SpaceGrotesk-Regular',
    color: 'white',
  },
});